Write entire compressed packet at once
Tnze/go-mc pull request #236
Opened 2023-03-30 22:42 UTC by richgrov

More discussion on #234

2023-03-31 04:12 UTC, Tnze requested changes
I'm sorry but it looks so ugly.

You could provide `.Len()` for VarInt. Alignments is the packing function's work.

2023-03-31 04:21 UTC, Tnze commented
And should definitely consider negative VarInts.

2023-03-31 20:28 UTC, richgrov commented
I didn't realize you already added the Len() functions, so I merged those along with changing the old functions into WriteToBytes()

2023-04-01 00:19 UTC, Tnze approved these changes

2023-04-01 01:57 UTC, merged